In [4]:
#1.Import the numpy package under the name np
import numpy as np

In [5]:
#2. Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/hp/anaconda3/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.

In [6]:
#3. Create a null vector of size 10
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#5. How to get the documentation of the numpy add function from the command line?
import numpy;


In [8]:
#6. Create a null vector of size 10 but the fifth value which is 1 
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
#7. Create a vector with values ranging from 10 to 49
x = np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [13]:
#8. Reverse a vector (first element becomes last)
x = np.arange(0,11)
x = x[: :-1]
print(x)

[10  9  8  7  6  5  4  3  2  1  0]


In [15]:
#9.Create a 3x3 matrix with values ranging from 0 to 8
x = np.arange(0,9)
arr1 = x.reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.nonzero([1,2,0,0,4,0])
print(x)
              


(array([0, 1, 4], dtype=int64),)


In [26]:
#11.Create a 3x3 identity matrix
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
#12.Create a 3x3x3 array with random values
x = np.random.random((3,3,3))
print(x)

[[[0.10802804 0.3287971  0.35457132]
  [0.80175964 0.83398047 0.41007846]
  [0.20253401 0.80108887 0.40638675]]

 [[0.34486395 0.24165861 0.92626826]
  [0.72971773 0.47450164 0.91264577]
  [0.86065628 0.23980216 0.98548935]]

 [[0.94379455 0.11998538 0.07987286]
  [0.04010569 0.88997231 0.77682605]
  [0.34760019 0.02518532 0.77818834]]]


In [33]:
#13. Create a 10x10 array with random values and find the minimum and maximum values 
x = np.random.random((10,10))
min = x.min()
max = x.max()
print(min)
print(max)

0.0011145134188758066
0.9894102843212736


In [34]:
#14.Create a random vector of size 30 and find the mean value
x = np.random.random(30)
m = x.mean()
print(m)

0.4530847041309869


In [39]:
#15.Create a 2d array with 1 on the border and 0 inside
x = np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
#16. How to add a border (filled with 0's) around an existing array?
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
#17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [43]:
#18.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

x = np.diag(1+np.arange(4), k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [51]:
#19 .Create a 8x8 matrix and fill it with a checkerboard pattern 
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [52]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [55]:
#21.. Create a checkerboard 8x8 matrix using the tile function 
array = np.array([[1,0],[0,1]])
y = np.tile(array,(4,4))
print (y)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [56]:
#22. Normalize a 5x5 random matrix 
x = np.random.random((5,5))
max = x.max()
min = x.min()
mm = (x-min)/(x-max)
print(mm)

[[-2.22579388e+01 -1.82612279e-01 -1.78594742e+00 -1.23731616e+00
  -7.36491917e+02]
 [-5.32489052e-01 -4.78130335e-01 -1.13679182e-01 -2.00664080e-01
  -3.67533357e+00]
 [-0.00000000e+00 -8.48860993e-01 -4.98685749e+00             inf
  -1.83784773e+02]
 [-2.59904411e+00 -8.32752838e-01 -1.22957451e+03 -1.15342996e+01
  -1.78952152e+00]
 [-2.82039877e-03 -2.16332755e+00 -5.04151029e-01 -3.76822254e+00
  -1.02934363e+00]]


C:\Users\hp\anaconda3\anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


In [57]:
#23.Create a custom dtype that describes a color as four unsigned bytes


In [60]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product
x = np.dot(np.ones((5,3)),np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [61]:
#25 Given a 1D array, negate all elements which are between 3 and 8, in place


In [62]:
#26What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [65]:
#27  Consider an integer vector Z, which of these expressions are legal? (★☆☆)


In [66]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\hp\anaconda3\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\hp\anaconda3\anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-2.14748365e+09])

In [69]:
#29 How to round away from zero a float array ?
np.around([0.37,4.7])

array([0., 5.])

In [73]:
#30 How to find common values between two arrays?
arr1 = np.array([0,1,2,3,4,5,6])
arr2 = np.array([0,1,6,8,9,10,11])
print(np.intersect1d(arr1,arr2))

[0 1 6]


In [74]:
#31 How to ignore all numpy warnings (not recommended)?

In [75]:
#32  Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\hp\anaconda3\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [76]:
#33  How to get the dates of yesterday, today and tomorrow? 

In [77]:
#34 How to get all the dates corresponding to the month of July 2016? 
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [78]:
#35 How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [86]:
#36  Extract the integer part of a random array using 5 different methods
x = np.random.uniform(0,10,10)
print(x-x%1)
print(np.floor(x))
print(np.ceil(x))
print(x.astype(int))
print(np.trunc(x))

[7. 7. 4. 8. 6. 0. 6. 4. 3. 9.]
[7. 7. 4. 8. 6. 0. 6. 4. 3. 9.]
[ 8.  8.  5.  9.  7.  1.  7.  5.  4. 10.]
[7 7 4 8 6 0 6 4 3 9]
[7. 7. 4. 8. 6. 0. 6. 4. 3. 9.]


In [87]:
#37  Create a 5x5 matrix with row values ranging from 0 to 4
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [90]:
#38 Consider a generator function that generates 10 integers and use it to build an array 
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [91]:
#39  Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [93]:
#40.Create a random vector of size 10 and sort it
x = random.random(10)
x.sort()
print(x)

[0.05659385 0.09789702 0.33833035 0.3702781  0.43813418 0.44619077
 0.82746787 0.84047081 0.91636599 0.92047773]


In [94]:
 #41 How to sum a small array faster than np.sum?
x = np.arange(10)
np.add.reduce(x)

45

In [96]:
#42 Consider two random array A and B, check if they are equal
arr1 = np.random.random(0,3,7)
arr2 = np.random.random(0,3,7)
equal = np.allclose(arr1,arr2)
print(equal)
equal = np.array_array(arr1,arr2)
print(equal)

TypeError: random() takes at most 1 positional argument (3 given)

In [100]:
#43 Make an array immutable (read-only) 
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

In [103]:
#44 Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

#### 

In [107]:
#45 Create random vector of size 10 and replace the maximum value by 0 
x = np.random.random(10)
x[x.argmax()] = 0
print(x)


[0.         0.37181961 0.88778327 0.42923615 0.8982144  0.85096431
 0.87161809 0.04571395 0.27890008 0.55319031]


In [105]:
#46  Create a structured array with x and y coordinates covering the [0,1]x[0,1] area


In [108]:
#47  Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C)) 

3638.1636371179666


In [109]:
#48  Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [110]:
#49 How to print all the values of an array?


In [111]:
#50  How to find the closest value (to a given scalar) in a vector?
x = np.arange(50)
y = np.random.uniform(0,50)
index = (np.abs(x-y)).argmin()
print(index)

43


In [113]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b) 
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\hp\anaconda3\anaconda\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [114]:
#52 Consider a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.71224027 0.41410682 0.80986416 0.5558894  0.94645742
  0.32605544 0.55644384 0.33182791 0.19216975]
 [0.71224027 0.         0.71048317 0.387885   0.38095439 0.31996431
  0.58512683 0.91869662 0.9500109  0.66209947]
 [0.41410682 0.71048317 0.         0.58884672 0.36326998 1.02045039
  0.66389039 0.9622136  0.34791389 0.57490357]
 [0.80986416 0.387885   0.58884672 0.         0.25713416 0.66826087
  0.8347451  1.19330021 0.91938918 0.8512629 ]
 [0.5558894  0.38095439 0.36326998 0.25713416 0.         0.70091502
  0.62614211 0.98216434 0.67201502 0.6168309 ]
 [0.94645742 0.31996431 1.02045039 0.66826087 0.70091502 0.
  0.72286438 0.98138612 1.22607478 0.84186848]
 [0.32605544 0.58512683 0.66389039 0.8347451  0.62614211 0.72286438
  0.         0.35887165 0.6578363  0.14535905]
 [0.55644384 0.91869662 0.9622136  1.19330021 0.98216434 0.98138612
  0.35887165 0.         0.8405315  0.39021608]
 [0.33182791 0.9500109  0.34791389 0.91938918 0.67201502 1.22607478
  0.6578363  0.84053

In [115]:
#53How to convert a float (32 bits) array into an integer (32 bits) in place?
x = np.arange(10,dtype= np.float32)
y = x.astype(np.int32 , copy = False)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [116]:
#54 How to read the following file? 
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

SyntaxError: invalid syntax (<ipython-input-116-2fab5acac6fc>, line 3)

In [118]:
#55 What is the equivalent of enumerate for numpy arrays?
x= np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [119]:
#56 Generate a generic 2D Gaussian-like array 
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [120]:
#57How to randomly place p elements in a 2D array? 
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [121]:
#58 Subtract the mean of each row of a matrix 
x = np.random.rand(5,10)
y = x-x.mean(axis = 1).reshape(-1,1)
print(y)

[[ 0.26329456  0.06369083  0.13655315 -0.34809286 -0.24858602  0.1657147
  -0.26142142  0.38005503  0.16273962 -0.31394759]
 [ 0.40485623 -0.48928908 -0.28743789 -0.24158963  0.24280604  0.22282487
   0.38827017 -0.04481965  0.05038613 -0.24600719]
 [ 0.35067821 -0.28263858 -0.24712402  0.07670718  0.24606823  0.07577598
   0.04149104 -0.26328241 -0.36882528  0.37114967]
 [-0.08047351 -0.06103734 -0.3073865   0.24932235 -0.13009258 -0.33885373
   0.35555402 -0.24939899  0.22865481  0.33371147]
 [ 0.37129335  0.27896428 -0.27892865 -0.04872717  0.20228294 -0.41727648
  -0.01511559 -0.20323968  0.34804458 -0.23729759]]


In [124]:
#59 How to sort an array by the nth column? 
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])


[[2 2 3]
 [4 5 7]
 [0 4 3]]
[[2 2 3]
 [0 4 3]
 [4 5 7]]


In [126]:
#60  How to tell if a given 2D array has null columns? 
x = np.random.uniform(0,3,(3,10))
print((~x.any(axis=0)).any())

False


In [127]:
#61  Find the nearest value from a given value in an array
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4245835351857511


In [128]:
#62Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
arr1 = np.arange(3).reshape(3,1)
arr2 = np.arange(3).rshape(1,3)
it = np.nditer([arr1,arr2,none])
for x,y,z in it: z[]

SyntaxError: invalid syntax (<ipython-input-128-bd90beb3a8ec>, line 5)

In [129]:
#63  Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [130]:
#64 Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[4. 5. 6. 2. 1. 2. 3. 1. 4. 2.]


In [133]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
x = [1,2,3,4,5,6,7]
y = [3,4,5,7,2,6,9]
f = np.bincount(y,x)
print(f)

[0. 0. 5. 1. 2. 3. 6. 4. 0. 7.]


In [134]:
#66 considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors


In [136]:
#67 Considering a four dimensions array, how to get sum over the last two axis at once?
x = np.random.randint(0,10,(3,4,3,4))
sum =x.sum(axis=(-2,-1))
print(sum)


[[63 46 91 59]
 [48 44 52 53]
 [61 71 57 59]]


In [141]:
#68 Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size descr0ibing subset indices?
d = np.random.uniform(0,1,100)
s = np.random.randint(0,10,100)
d_sums = np.bincount(s, weights=d)
d_counts = np.bincount(s)
d_means = d_sums / d_counts
print(d_means)


[0.49271756 0.50564287 0.57057565 0.39654172 0.35782125 0.46709919
 0.53739178 0.63318703 0.52437259 0.56536761]


In [144]:
#69 How to get the diagonal of a dot product?
x = np.random.uniform(0,1,(3,3))
y = np.random.uniform(0,1,(3,3))
print(x,y)
np.diag(np.dot(x,y))

[[0.13556914 0.58068399 0.09016502]
 [0.51032572 0.44013549 0.97455009]
 [0.10633033 0.45543242 0.14399924]] [[0.41088683 0.88743224 0.41371068]
 [0.47644175 0.64231858 0.23077166]
 [0.20622598 0.29801575 0.02199915]]


array([0.35096004, 1.02601798, 0.15225875])

In [145]:
#70 Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [148]:
#71Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x*y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [152]:
#72  How to swap two rows of an array? 
x = np.arange(25)
y = x.reshape(5,5)
y[[0,1]] = y[[1,0]]
print(y)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [153]:
#73 Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles


In [155]:
#74Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


In [156]:
#75 How to compute averages using a sliding window over an array?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [157]:
#76 Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [158]:
#77 How to negate a boolean, or to change the sign of a float inplace?
x= np.random.randint(0,2,100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([ 0.0296873 ,  0.37244883,  0.81893524,  0.17617923,  0.74573067,
        0.04495426, -0.74784548, -0.30542917, -0.52434638,  0.96617289,
        0.79538993, -0.00247917, -0.81090578,  0.67464427,  0.81129607,
        0.6456021 , -0.30010407,  0.54846523, -0.3812647 ,  0.65055452,
       -0.9862705 , -0.7862356 , -0.06851082,  0.17117531,  0.35041786,
        0.61823203,  0.69448889, -0.55072192,  0.09609176, -0.60015171,
        0.47554258,  0.70420558, -0.76848453, -0.49161971,  0.42357833,
       -0.98420074, -0.90491284, -0.86430329, -0.66974521,  0.56753123,
       -0.96650795,  0.26044261,  0.67472949, -0.4233903 , -0.47340237,
       -0.24359167, -0.02133327,  0.75780289,  0.94395642,  0.75776248,
       -0.87236569, -0.78553194, -0.75525025, -0.60946349,  0.06457264,
        0.82258401, -0.58686398, -0.64443908, -0.4847815 , -0.32480932,
       -0.51729209,  0.98332121,  0.39848714, -0.88908944,  0.69406523,
        0.26704765, -0.11406359, -0.53756654,  0.0888221 , -0.68

In [159]:
#78 Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.49557177 8.98354131 4.84644151 3.09068767 0.92772598 1.72414533
 2.25133176 4.52219178 3.95054447 3.54398127]


In [160]:
#79 Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.35471151  1.88768534  4.30046598  1.37328309  1.52225108 12.32826632
   1.45109933  6.41960054  6.74409853  3.48835738]
 [ 9.14924091  6.46601729  2.69841968  6.80686496  3.03642066  4.50215871
   4.34341163  1.67522085  2.0803505   5.62746258]
 [ 3.05257207  5.50518501  5.24336716  5.00669834  1.24193969 15.97549751
   1.7532296   8.05264132 10.26878475  4.76107656]
 [11.5621858   1.43521156  3.54584187  1.25592062  6.7873522  12.8278067
   6.75637823  0.7151579   5.20512619 11.46889852]
 [ 6.33008683  7.03870777  0.13557503  7.50037423  0.0636519   3.58936612
   1.52425455  0.49837004  2.25298877  2.56950161]
 [ 8.99232184  7.66980812  2.76863374  8.02657552  2.68016575  3.25835493
   4.18648937  2.00023614  3.21864985  4.94742368]
 [ 8.01225184  2.56266323  0.01712107  2.24573883  3.3449314  13.56025063
   3.20644526  2.72539928  6.76814943  8.42246377]
 [11.61086679  3.87984834  3.14784928  3.72174653  7.23505815 15.3221165
   6.80506557  0.17391282  7.55305374 12.58091169]
 [

In [161]:
#80Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [163]:
#81Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 
x = np.arange(1,15,dtype=np.uint32)
y = stride_tricks.as_strided(x,(11,4),(4,4))
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [166]:
#82 Compute a matrix rank 
x = np.random.uniform(0,1(10,10))
U, S, V = np.linalg.svd(x) 
rank = np.sum(S > 1e-10)
print(rank)

TypeError: 'int' object is not callable

In [168]:
#83 How to find the most frequent value in an array?
x = np.random.randint(0,20,40)
print(np.bincount(x).argmax())

14


In [170]:
#84 Extract all the contiguous 3x3 blocks from a random 10x10 matrix
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 4 0]
   [1 4 1]
   [1 2 1]]

  [[4 0 2]
   [4 1 3]
   [2 1 1]]

  [[0 2 4]
   [1 3 1]
   [1 1 3]]

  [[2 4 2]
   [3 1 0]
   [1 3 1]]

  [[4 2 4]
   [1 0 3]
   [3 1 0]]

  [[2 4 0]
   [0 3 1]
   [1 0 4]]

  [[4 0 4]
   [3 1 4]
   [0 4 1]]

  [[0 4 0]
   [1 4 4]
   [4 1 0]]]


 [[[1 4 1]
   [1 2 1]
   [4 1 3]]

  [[4 1 3]
   [2 1 1]
   [1 3 1]]

  [[1 3 1]
   [1 1 3]
   [3 1 1]]

  [[3 1 0]
   [1 3 1]
   [1 1 0]]

  [[1 0 3]
   [3 1 0]
   [1 0 4]]

  [[0 3 1]
   [1 0 4]
   [0 4 2]]

  [[3 1 4]
   [0 4 1]
   [4 2 1]]

  [[1 4 4]
   [4 1 0]
   [2 1 1]]]


 [[[1 2 1]
   [4 1 3]
   [0 2 3]]

  [[2 1 1]
   [1 3 1]
   [2 3 2]]

  [[1 1 3]
   [3 1 1]
   [3 2 0]]

  [[1 3 1]
   [1 1 0]
   [2 0 2]]

  [[3 1 0]
   [1 0 4]
   [0 2 1]]

  [[1 0 4]
   [0 4 2]
   [2 1 1]]

  [[0 4 1]
   [4 2 1]
   [1 1 0]]

  [[4 1 0]
   [2 1 1]
   [1 0 3]]]


 [[[4 1 3]
   [0 2 3]
   [1 1 0]]

  [[1 3 1]
   [2 3 2]
   [1 0 3]]

  [[3 1 1]
   [3 2 0]
   [0 3 4]]

  [[1 1 0]
   [2 0 2]
   [3 4 0]]

  [[1 0 4]
   

In [172]:
#85 Create a 2D array subclass such that Z[i,j] == Z[j,i] 
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 11  9  9  5]
 [11  6 18  0 13]
 [ 9 18  1 42 10]
 [ 9  0 42  8  6]
 [ 5 13 10  6  4]]


In [173]:
#86 Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [175]:
#87  Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 
x = np.ones((16,16))
y = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], y), axis=0),
                                       np.arange(0, x.shape[1], y), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [179]:
 #88 How to implement the Game of Life using numpy arrays?
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 1 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [180]:
#89  How to get the n largest values of an array
x = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (x[np.argsort(x)[-n:]])


[9995 9996 9997 9998 9999]


In [181]:
#90 Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [182]:
#91 How to create a record array from a regular array?
x = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
y = np.core.records.fromarrays(x.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(y)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [183]:
#92 Consider a large vector Z, compute Z to the power of 3 using 3 different methods
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

In [184]:
#93  Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
x = np.random.randint(0,5,(8,3))
y = np.random.randint(0,5,(2,2))

z = (x[..., np.newaxis, np.newaxis] == y)
rows = np.where(z.any((3,1)).all(1))[0]
print(rows)

[0 2 4 5 6]


In [185]:
#94 Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 3 0]
 [0 1 1]
 [3 4 0]
 [0 1 2]
 [3 1 4]
 [4 3 0]
 [1 4 2]
 [3 1 4]
 [0 2 2]
 [4 0 3]]
[[0 3 0]
 [0 1 1]
 [3 4 0]
 [0 1 2]
 [3 1 4]
 [4 3 0]
 [1 4 2]
 [3 1 4]
 [0 2 2]
 [4 0 3]]
[[0 3 0]
 [0 1 1]
 [3 4 0]
 [0 1 2]
 [3 1 4]
 [4 3 0]
 [1 4 2]
 [3 1 4]
 [0 2 2]
 [4 0 3]]


In [186]:
#95  Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])



I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [187]:
#96 Given a two dimensional array, how to extract unique rows? 


In [188]:
#97  Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)  
np.einsum('i,j->ij', A, B) 

array([[0.0475827 , 0.00700072, 0.01489224, 0.03974671, 0.04684446,
        0.00662453, 0.01625547, 0.0348    , 0.01844673, 0.03819381],
       [0.04124992, 0.00606899, 0.01291023, 0.03445683, 0.04060993,
        0.00574287, 0.01409203, 0.03016847, 0.01599166, 0.0331106 ],
       [0.80999673, 0.11917272, 0.25350948, 0.67660536, 0.79742977,
        0.11276885, 0.27671558, 0.5923978 , 0.31401739, 0.6501704 ],
       [0.79735636, 0.11731297, 0.24955335, 0.66604663, 0.78498551,
        0.11100904, 0.27239731, 0.58315316, 0.30911701, 0.64002419],
       [0.40113438, 0.05901786, 0.12554541, 0.33507502, 0.39491085,
        0.05584647, 0.13703776, 0.29337294, 0.15551072, 0.32198365],
       [0.59129312, 0.08699542, 0.18506051, 0.49391817, 0.58211931,
        0.08232063, 0.20200084, 0.43244711, 0.22923095, 0.47462079],
       [0.53253172, 0.07835001, 0.16666961, 0.44483367, 0.52426958,
        0.07413979, 0.18192644, 0.38947147, 0.20645049, 0.42745402],
       [0.59542722, 0.08760366, 0.1863543

In [189]:
#98  Considering a path described by two vectors (X,Y), how to sample it using equidistant samples


In [190]:
#99  Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [ ]:
#100 Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)